apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
    owner: tmagikar_nginx_serv
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 192.168.99.151
  ports:
      - protocol: TCP
        name: http
        port: 80
        targetPort: 80
      - protocol: TCP
        name: https
        port: 443
        targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    owner: tmagikar_nginx_depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        owner: tmagikar_nginx_depl
    spec:
      containers:
      - name: nginx
        image: nginx_image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443